# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
spring:
  # ====================================================================================================================
  # = DEVTOOLS
  # ====================================================================================================================
  devtools:
    livereload:
      port: 35730

  # ====================================================================================================================
  # = MESSAGES
  # ====================================================================================================================
  messages:
    cache-duration: 1

  # ====================================================================================================================
  # = THYMELEAF
  # ====================================================================================================================
  thymeleaf:
    cache: false

# ======================================================================================================================
# = LOGGING
# ======================================================================================================================
logging:
  level:
    com:
      github:
        computerhuis:
          portaal: DEBUG
